// Synthetic demo leads. 24 prospects covering the seeded archetype mix.
// Workstream 2 may replace this with a CSV fixture; the API layer can also
// parse a CSV via /prospects/upload-csv.

export type DemoLead = {
  firstName: string;
  lastName: string;
  email: string;
  title: string;
  company: string;
  industry: string;
  companySize: string;
  notes: string;
  trigger: string;
  website: string;
  linkedinSummary: string;
  // Hint for matcher in safe mode. Real matching does not depend on this.
  archetypeHint: string;
};

export const SAMPLE_LEADS: DemoLead[] = [
  {
    firstName: "Maya",
    lastName: "Holloway",
    email: "maya@northpinestudio.test",
    title: "Founder",
    company: "Northpine Studio",
    industry: "Brand & creative",
    companySize: "12",
    notes: "Mentioned losing warm leads on a podcast last month.",
    trigger: "Hiring a growth lead",
    website: "northpinestudio.test",
    linkedinSummary: "Founder of a 12-person brand studio in Brooklyn.",
    archetypeHint: "Overworked Agency Owner",
  },
  {
    firstName: "Owen",
    lastName: "Petrov",
    email: "owen@petrovconsulting.test",
    title: "Independent consultant",
    company: "Petrov Consulting",
    industry: "Strategy",
    companySize: "1",
    notes: "Posts skeptical takes on AI follow-up tools.",
    trigger: "Wrote 'Why most cold outbound is theater' last week",
    website: "petrovconsulting.test",
    linkedinSummary: "Solo strategy consultant ex-McKinsey.",
    archetypeHint: "Skeptical Solo Consultant",
  },
  {
    firstName: "Dana",
    lastName: "Akhtar",
    email: "dana@stencilcollective.test",
    title: "Operations manager",
    company: "Stencil Collective",
    industry: "Design studios",
    companySize: "22",
    notes: "Runs ops for a 22-person creative studio.",
    trigger: "Hired a junior ops admin two weeks ago",
    website: "stencilcollective.test",
    linkedinSummary: "Operations lead, six years at the studio.",
    archetypeHint: "Ops-Minded Studio Manager",
  },
  {
    firstName: "Ravi",
    lastName: "Murthy",
    email: "ravi@latticegrowth.test",
    title: "Founder",
    company: "Lattice Growth",
    industry: "Growth marketing",
    companySize: "9",
    notes: "Tracks pipeline metrics weekly. Tweets pipeline screenshots.",
    trigger: "Posted about leaky inbound funnel",
    website: "latticegrowth.test",
    linkedinSummary: "Founder building a growth-led services agency.",
    archetypeHint: "Growth-Focused Founder",
  },
  {
    firstName: "Sloane",
    lastName: "Becker",
    email: "sloane@junipergroup.test",
    title: "COO",
    company: "Juniper Group",
    industry: "Multi-service agency",
    companySize: "30",
    notes: "Has churned out of two follow-up SaaS tools in 18 months.",
    trigger: "Asked for SaaS recommendations on a peer Slack",
    website: "junipergroup.test",
    linkedinSummary: "COO with 12 years in agency operations.",
    archetypeHint: "Tool-Fatigued Operator",
  },
  {
    firstName: "Jules",
    lastName: "Caron",
    email: "jules@bootstrapbureau.test",
    title: "Founder",
    company: "Bootstrap Bureau",
    industry: "B2B services",
    companySize: "4",
    notes: "Bootstrapped, frugal, runs everything from Gmail and Sheets.",
    trigger: "Posted 'tell me your cheapest SaaS stack'",
    website: "bootstrapbureau.test",
    linkedinSummary: "Bootstrapped founder, 4 years in.",
    archetypeHint: "Budget-Sensitive Operator",
  },
  {
    firstName: "Priya",
    lastName: "Singh",
    email: "priya@meridianlegalops.test",
    title: "Director",
    company: "Meridian Legal Ops",
    industry: "Legal services",
    companySize: "18",
    notes: "Compliance-first. Long vendor reviews.",
    trigger: "Hired a procurement lead",
    website: "meridianlegalops.test",
    linkedinSummary: "Director of legal operations at a 18-person practice.",
    archetypeHint: "Trust-First Buyer",
  },
  {
    firstName: "Elena",
    lastName: "Rivers",
    email: "elena@assist.test",
    title: "Executive assistant",
    company: "Brightline Group",
    industry: "Consulting",
    companySize: "40",
    notes: "Filters founder's inbox. Redirects vendor pitches.",
    trigger: "n/a",
    website: "brightlinegroup.test",
    linkedinSummary: "EA to the managing partner.",
    archetypeHint: "Wrong-Person Gatekeeper",
  },
  {
    firstName: "Felix",
    lastName: "Reyes",
    email: "felix@altitudepartners.test",
    title: "Founder",
    company: "Altitude Partners",
    industry: "Established agency",
    companySize: "55",
    notes: "Already uses a follow-up automation tool with a 12-month contract.",
    trigger: "Renewed CRM last quarter",
    website: "altitudepartners.test",
    linkedinSummary: "Founder of an established 55-person agency.",
    archetypeHint: "Competitor-Locked Buyer",
  },
  {
    firstName: "Tomi",
    lastName: "Adekunle",
    email: "tomi@ridgelinegrowth.test",
    title: "Founder",
    company: "Ridgeline Growth",
    industry: "Growth services",
    companySize: "14",
    notes: "Curious about the space but Q2 is roadmap-locked.",
    trigger: "Said 'reach out next quarter' to two vendors",
    website: "ridgelinegrowth.test",
    linkedinSummary: "Growing services founder with a 6-month roadmap.",
    archetypeHint: "Interested-But-Later Buyer",
  },
  {
    firstName: "Nadia",
    lastName: "Brooks",
    email: "nadia@kestrelhouse.test",
    title: "Managing director",
    company: "Kestrel House",
    industry: "Boutique services",
    companySize: "16",
    notes: "Founder mode. Drowning in client delivery.",
    trigger: "Posted about losing a warm lead because she forgot to follow up",
    website: "kestrelhouse.test",
    linkedinSummary: "Managing director of a 16-person agency.",
    archetypeHint: "Overworked Agency Owner",
  },
  {
    firstName: "Hugo",
    lastName: "Marsh",
    email: "hugo@marshanalysis.test",
    title: "Independent consultant",
    company: "Marsh Analysis",
    industry: "Strategy",
    companySize: "1",
    notes: "Skeptical, wants proof points before any pitch.",
    trigger: "Asked 'who has actually seen this work?' in a peer group",
    website: "marshanalysis.test",
    linkedinSummary: "Solo consultant, ex-strategy partner.",
    archetypeHint: "Skeptical Solo Consultant",
  },
  {
    firstName: "Imani",
    lastName: "Carter",
    email: "imani@cleftstudio.test",
    title: "Operations lead",
    company: "Cleft Studio",
    industry: "Design studio",
    companySize: "18",
    notes: "Runs ops + light marketing. Plug-and-play preference.",
    trigger: "Set up a new HubSpot Lite instance",
    website: "cleftstudio.test",
    linkedinSummary: "Ops lead, 4 years at the studio.",
    archetypeHint: "Ops-Minded Studio Manager",
  },
  {
    firstName: "Kai",
    lastName: "Yamamoto",
    email: "kai@compassgrowth.test",
    title: "Founder",
    company: "Compass Growth",
    industry: "B2B services",
    companySize: "11",
    notes: "Pipeline obsessive. Tweets weekly metrics.",
    trigger: "Inbound dipped 14% this month",
    website: "compassgrowth.test",
    linkedinSummary: "Founder, 6 years building a growth services agency.",
    archetypeHint: "Growth-Focused Founder",
  },
  {
    firstName: "Marcus",
    lastName: "Levitt",
    email: "marcus@harborgrove.test",
    title: "COO",
    company: "Harborgrove Group",
    industry: "Multi-service agency",
    companySize: "28",
    notes: "Visibly tired of vendor pitches. Has a 'no new tools' policy this year.",
    trigger: "Posted 'we are not adopting any new SaaS in H1'",
    website: "harborgrove.test",
    linkedinSummary: "COO with a long history of agency turnarounds.",
    archetypeHint: "Tool-Fatigued Operator",
  },
  {
    firstName: "Saanvi",
    lastName: "Mehta",
    email: "saanvi@solomet.test",
    title: "Founder",
    company: "Solomet",
    industry: "Bootstrapped services",
    companySize: "3",
    notes: "Watching every dollar. Asks about ROI early.",
    trigger: "Posted 'cheapest CRM that doesn't suck?'",
    website: "solomet.test",
    linkedinSummary: "Bootstrapped founder, three-person team.",
    archetypeHint: "Budget-Sensitive Operator",
  },
  {
    firstName: "Daniel",
    lastName: "Voss",
    email: "daniel@vossconsult.test",
    title: "Partner",
    company: "Voss Consult",
    industry: "Regulated services",
    companySize: "20",
    notes: "Compliance-first. Methodical.",
    trigger: "Hired a procurement officer",
    website: "vossconsult.test",
    linkedinSummary: "Partner at a regulated services firm.",
    archetypeHint: "Trust-First Buyer",
  },
  {
    firstName: "Brielle",
    lastName: "Owens",
    email: "brielle@assist.test",
    title: "Executive assistant",
    company: "Lumen & Co",
    industry: "Consulting",
    companySize: "60",
    notes: "Polite gatekeeper. Will redirect.",
    trigger: "n/a",
    website: "lumenandco.test",
    linkedinSummary: "EA to the managing director.",
    archetypeHint: "Wrong-Person Gatekeeper",
  },
  {
    firstName: "Theo",
    lastName: "Park",
    email: "theo@oakridgeagency.test",
    title: "Founder",
    company: "Oakridge Agency",
    industry: "Established agency",
    companySize: "70",
    notes: "Already locked into a follow-up automation contract.",
    trigger: "Posted about CRM renewal",
    website: "oakridgeagency.test",
    linkedinSummary: "Founder of a 70-person agency, 12 years in.",
    archetypeHint: "Competitor-Locked Buyer",
  },
  {
    firstName: "Ines",
    lastName: "Arroyo",
    email: "ines@summitwave.test",
    title: "Founder",
    company: "Summit Wave",
    industry: "Growth services",
    companySize: "10",
    notes: "Q3 roadmap is fixed; willing to chat for later.",
    trigger: "Said 'reach out in Q3'",
    website: "summitwave.test",
    linkedinSummary: "Growing services founder.",
    archetypeHint: "Interested-But-Later Buyer",
  },
  {
    firstName: "Jonas",
    lastName: "Klein",
    email: "jonas@kleinandco.test",
    title: "Founder",
    company: "Klein & Co",
    industry: "Boutique services",
    companySize: "8",
    notes: "Owns sales and delivery. Mentions losing pipeline often.",
    trigger: "Posted about delivery vs sales tradeoff",
    website: "kleinandco.test",
    linkedinSummary: "Founder, hands-on operator.",
    archetypeHint: "Overworked Agency Owner",
  },
  {
    firstName: "Quinn",
    lastName: "Walters",
    email: "quinn@walterspartners.test",
    title: "COO",
    company: "Walters Partners",
    industry: "Multi-service agency",
    companySize: "25",
    notes: "Burned by two follow-up tools in the last year.",
    trigger: "Posted 'why does every CRM need a 6-week onboarding?'",
    website: "walterspartners.test",
    linkedinSummary: "COO frustrated with implementation overhead.",
    archetypeHint: "Tool-Fatigued Operator",
  },
  {
    firstName: "Aisha",
    lastName: "Bello",
    email: "aisha@belloagency.test",
    title: "Operations manager",
    company: "Bello Agency",
    industry: "Creative services",
    companySize: "15",
    notes: "Wants integrations with Gmail and HubSpot.",
    trigger: "Hired a marketing operations contractor",
    website: "belloagency.test",
    linkedinSummary: "Ops manager at a creative services firm.",
    archetypeHint: "Ops-Minded Studio Manager",
  },
  {
    firstName: "Ethan",
    lastName: "Ng",
    email: "ethan@helmgrowth.test",
    title: "Founder",
    company: "Helm Growth",
    industry: "Growth marketing",
    companySize: "13",
    notes: "Builds dashboards. Asks 'show me the metric'.",
    trigger: "Inbound conversion fell 9%",
    website: "helmgrowth.test",
    linkedinSummary: "Metrics-driven growth founder.",
    archetypeHint: "Growth-Focused Founder",
  },
];
