import type { ArchetypeSeed } from "../db/repositories/archetypes";

type DemoArchetypeBlueprint = Omit<ArchetypeSeed, "offerId">;

export const SAMPLE_ARCHETYPES: DemoArchetypeBlueprint[] = [
  {
    name: "Overworked Agency Owner",
    segment: "Boutique services",
    role: "Founder / Managing Director",
    initialVersion: {
      description:
        "Runs a 5-25 person agency. Lives in client delivery and treats follow-up as a chore.",
      currentWorkflow: "Inbox + calendar + spreadsheet of inbound leads.",
      painIntensity: 0.85,
      buyingPower: 0.9,
      riskTolerance: 0.4,
      voiceStyle: "Direct, busy, slightly cynical",
      predictedObjections: ["Pricing", "Time to set up"],
      preferredAngles: ["Pipeline recovery", "We draft, you approve"],
      dislikedPhrases: ["AI-powered automation platform", "Revolutionary"],
      likelyReplyPatterns: ["Short forwards to ops manager", "Reply with one line"],
      confidence: 0.7,
    },
  },
  {
    name: "Skeptical Solo Consultant",
    segment: "Solo consulting",
    role: "Independent consultant",
    initialVersion: {
      description:
        "Solo strategy or growth consultant. Trusts only what they have already seen work.",
      currentWorkflow: "Notion + email + manual nudges.",
      painIntensity: 0.55,
      buyingPower: 0.5,
      riskTolerance: 0.3,
      voiceStyle: "Wary, analytical",
      predictedObjections: ["Trust", "Authenticity"],
      preferredAngles: ["Human in the loop", "Proof point first"],
      dislikedPhrases: ["10x your pipeline", "Cold outbound"],
      likelyReplyPatterns: ["Polite skeptic question", "What is the actual proof"],
      confidence: 0.6,
    },
  },
  {
    name: "Ops-Minded Studio Manager",
    segment: "Creative studios",
    role: "Operations manager",
    initialVersion: {
      description:
        "Owns operations for a 10-30 person studio. Wants implementation-light tools.",
      currentWorkflow: "Notion + Slack + HubSpot Lite.",
      painIntensity: 0.7,
      buyingPower: 0.4,
      riskTolerance: 0.5,
      voiceStyle: "Practical, list-driven",
      predictedObjections: ["Implementation effort", "Integration with existing CRM"],
      preferredAngles: ["No new tool to learn", "Plug into Gmail"],
      dislikedPhrases: ["Migration", "Re-engineer your funnel"],
      likelyReplyPatterns: ["Asks about integration", "Loops in CEO"],
      confidence: 0.65,
    },
  },
  {
    name: "Growth-Focused Founder",
    segment: "B2B services",
    role: "Founder",
    initialVersion: {
      description: "Founder who tracks pipeline weekly and notices quiet leads quickly.",
      currentWorkflow: "HubSpot + spreadsheet + weekly pipeline review.",
      painIntensity: 0.8,
      buyingPower: 0.85,
      riskTolerance: 0.7,
      voiceStyle: "Crisp, metrics-driven",
      predictedObjections: ["Already have a process"],
      preferredAngles: ["Pipeline recovery numbers"],
      dislikedPhrases: ["Spray and pray"],
      likelyReplyPatterns: ["Asks for a metric", "Proposes a quick call"],
      confidence: 0.75,
    },
  },
  {
    name: "Tool-Fatigued Operator",
    segment: "Multi-service agencies",
    role: "COO / Head of operations",
    initialVersion: {
      description:
        "Has been burned by SaaS tools that promise automation and require weeks of setup.",
      currentWorkflow: "Mixed CRMs, manual reminders, dashboards.",
      painIntensity: 0.7,
      buyingPower: 0.6,
      riskTolerance: 0.25,
      voiceStyle: "Tired, deliberate",
      predictedObjections: ["Pricing", "Yet another tool"],
      preferredAngles: ["Implementation-light", "Pricing is fair"],
      dislikedPhrases: ["Automation platform", "All-in-one"],
      likelyReplyPatterns: ["Pushes back on cost", "Asks about onboarding time"],
      confidence: 0.55,
    },
  },
  {
    name: "Budget-Sensitive Operator",
    segment: "Bootstrapped services",
    role: "Founder",
    initialVersion: {
      description: "Bootstrapped operator watching every monthly subscription.",
      currentWorkflow: "Gmail + spreadsheets, no CRM.",
      painIntensity: 0.5,
      buyingPower: 0.3,
      riskTolerance: 0.4,
      voiceStyle: "Frugal, honest",
      predictedObjections: ["Pricing", "ROI proof"],
      preferredAngles: ["Pay only when it works", "ROI in 30 days"],
      dislikedPhrases: ["Enterprise"],
      likelyReplyPatterns: ["Asks about pricing first"],
      confidence: 0.6,
    },
  },
  {
    name: "Trust-First Buyer",
    segment: "Regulated services",
    role: "Partner / Director",
    initialVersion: {
      description: "Needs proof, human approval, and compliance signals before adopting anything.",
      currentWorkflow: "Email-first, careful, slow vendor reviews.",
      painIntensity: 0.45,
      buyingPower: 0.7,
      riskTolerance: 0.2,
      voiceStyle: "Formal, measured",
      predictedObjections: ["Compliance", "Trust"],
      preferredAngles: ["Human approval required", "Compliance built in"],
      dislikedPhrases: ["Auto-send", "Hands-off"],
      likelyReplyPatterns: ["Asks who else uses it", "Asks about compliance"],
      confidence: 0.6,
    },
  },
  {
    name: "Wrong-Person Gatekeeper",
    segment: "Mid-market services",
    role: "Executive assistant",
    initialVersion: {
      description: "Filters founder inbox. Will redirect or ignore.",
      currentWorkflow: "Inbox triage on behalf of executive.",
      painIntensity: 0.1,
      buyingPower: 0.1,
      riskTolerance: 0.5,
      voiceStyle: "Polite, brief",
      predictedObjections: ["Wrong person"],
      preferredAngles: ["Short, respectful, easy to redirect"],
      dislikedPhrases: ["Long pitch"],
      likelyReplyPatterns: ["Wrong contact, please reach X"],
      confidence: 0.8,
    },
  },
  {
    name: "Competitor-Locked Buyer",
    segment: "Established agencies",
    role: "Founder",
    initialVersion: {
      description: "Already pays for an existing follow-up or CRM tool.",
      currentWorkflow: "Established stack with renewal cycles.",
      painIntensity: 0.4,
      buyingPower: 0.7,
      riskTolerance: 0.3,
      voiceStyle: "Polite, pragmatic",
      predictedObjections: ["Already using a competitor"],
      preferredAngles: ["Switch cost story", "Side-by-side comparison"],
      dislikedPhrases: ["Rip and replace"],
      likelyReplyPatterns: ["We already use X"],
      confidence: 0.65,
    },
  },
  {
    name: "Interested-But-Later Buyer",
    segment: "Growing agencies",
    role: "Founder",
    initialVersion: {
      description: "Curious, but timing is wrong this quarter.",
      currentWorkflow: "Manual follow-ups, growth roadmap planned.",
      painIntensity: 0.6,
      buyingPower: 0.7,
      riskTolerance: 0.55,
      voiceStyle: "Friendly, deferring",
      predictedObjections: ["Timing"],
      preferredAngles: ["Stay in touch with proof", "Pilot in 90 days"],
      dislikedPhrases: ["Buy now"],
      likelyReplyPatterns: ["Reach out in Q3"],
      confidence: 0.55,
    },
  },
];

// Calibration target archetype: matches the spec's mandatory v1 -> v2 moment.
export const TOOL_FATIGUED_OPERATOR_NAME = "Tool-Fatigued Operator";

export const TOOL_FATIGUED_OPERATOR_V2 = {
  reason:
    "Predictions framed pricing as the dominant objection. Replies showed implementation/timing concerns dominated and pricing concerns were rare.",
  description:
    "Has been burned by SaaS tools that promise automation and require weeks of setup. Cares far more about onboarding effort than monthly cost.",
  currentWorkflow: "Mixed CRMs, manual reminders, dashboards.",
  painIntensity: 0.75,
  buyingPower: 0.6,
  riskTolerance: 0.3,
  voiceStyle: "Tired, deliberate",
  predictedObjections: [
    "Implementation effort",
    "Yet another tool",
    "Time to first value",
  ],
  preferredAngles: [
    "Implementation-light copy",
    "We draft, you approve",
    "15-min fit check, not book a demo",
  ],
  dislikedPhrases: ["Automation platform", "All-in-one", "Migration"],
  likelyReplyPatterns: ["Asks about onboarding time", "Asks who is in the loop"],
  confidence: 0.78,
  added: [
    "I do not have time to set up another tool.",
    "Prefers 'we draft, you approve.'",
    "Prefers implementation-light messaging.",
    "Responds better to '15-min fit check' than 'book a demo.'",
  ],
  removedOrDownweighted: [
    "Over-weighted pricing objection.",
    "Disliked 'automation platform.'",
  ],
};
